[package]
name = "align-cli"
version = "0.3.0"
edition = "2021"
authors = ["Douwe Schulte <d.schulte@uu.nl>"]
description = "A command line interface for easily aligning two sequences."
license = "MIT"
repository = "https://github.com/snijderlab/align-cli"
readme = "README.md"
include = ["inc/**/*", "src/**/*", "LICENSE", "README.md"]

[[bin]]
name = "align"
path = "src/main.rs"

[dependencies]
bio = "1.2"
clap = { version = "4", features = ["derive", "cargo"] }
colored = "2"
imgt-germlines = { git = "https://github.com/snijderlab/imgt-germlines" }
rayon = "1.8"
rustyms = "0.7.0"
