[package]
name = "align-cli"
version = "0.4.0"
edition = "2021"
authors = ["Douwe Schulte <d.schulte@uu.nl>"]
description = "A command line interface for easily aligning sequences."
license = "MIT OR Apache-2.0"
repository = "https://github.com/snijderlab/align-cli"
readme = "README.md"
include = ["inc/**/*", "src/**/*", "LICENSE", "README.md"]
categories = ["science::bio"]
keywords = ["massspectrometry", "bio", "alignment", "proforma", "imgt"]

[[bin]]
name = "align"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive", "cargo"] }
colored = "2.1"
itertools = "0.12"
rayon = "1.8"
rustyms = "0.8.3"

[profile.release]
debug = true
opt-level = 3
lto = true
codegen-units = 1
