[package]
name = "align-cli"
version = "0.1.0"
edition = "2021"
authors = ["Douwe Schulte <d.schulte@uu.nl>"]
description = "A command line interface for easily aligning two sequences."
license = "MIT"
repository = "https://github.com/snijderlab/align"
readme = "README.md"
include = ["src/**/*", "LICENSE", "README.md"]

[[bin]]
name = "align"
path = "sc/main.rs"

[dependencies]
bio = "*"
clap ={version="4", features=["derive"]}
colored = "2"
rustyms = "*"