[package]
name = "align-cli"
version = "0.2.3"
edition = "2021"
authors = ["Douwe Schulte <d.schulte@uu.nl>"]
description = "A command line interface for easily aligning two sequences."
license = "MIT"
repository = "https://github.com/snijderlab/align-cli"
readme = "README.md"
include = ["inc/**/*", "src/**/*", "LICENSE", "README.md"]

[[bin]]
name = "align"
path = "src/main.rs"

[dependencies]
bio = "1.2"
clap ={version="4", features=["derive"]}
colored = "2"
rustyms = "0.3.0"