name: Rust

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release && strip target/release/align && mv target/release/align target/release/align_amd64

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/align_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: target/release/align_amd64
          name: align_amd64

  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/align.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: target/release/align.exe
          name: align.exe

  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-apple-darwin

      - name: Build for mac
        run: cargo build --release && strip target/release/align && mv target/release/align target/release/align_darwin

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/align_darwin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: target/release/align_darwin
          name: align_darwin
